/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual.endereco;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

import model.Endereco;

/**
 *
 * @author Victor
 */
public class AddEndereco extends javax.swing.JDialog {

    private Endereco endereco;
    public int check = 0;

    public AddEndereco(java.awt.Frame parent, boolean modal, Endereco endereco) {
        super(parent, modal);
        this.setTitle("Alterar Endereco");
        this.endereco = endereco;
        initComponents();
        formatarCampo();
        preencher(endereco);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGravar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFTId = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTBairro = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTLogradouro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFTNumero = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFTComplemento = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFTCep = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jButtonGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGravarKeyPressed(evt);
            }
        });

        jLabel2.setText("ID:");

        jFTId.setEditable(false);
        jFTId.setEnabled(false);

        jLabel3.setText("Bairro:");

        jLabel5.setText("Logradouro:");

        jFTLogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTLogradouroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTLogradouroFocusLost(evt);
            }
        });
        jFTLogradouro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTLogradouroMouseClicked(evt);
            }
        });
        jFTLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTLogradouroActionPerformed(evt);
            }
        });
        jFTLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTLogradouroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTLogradouroKeyTyped(evt);
            }
        });

        jLabel6.setText("Número:");

        jLabel4.setText("Complemento:");

        jLabel7.setText("CEP:");

        jFTCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTCepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTCepFocusLost(evt);
            }
        });
        jFTCep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTCepMouseClicked(evt);
            }
        });
        jFTCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTCepActionPerformed(evt);
            }
        });
        jFTCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTCepKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTCepKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTId, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jFTBairro)
                            .addComponent(jFTLogradouro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jFTCep)
                            .addComponent(jFTComplemento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFTId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jFTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFTLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jFTComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFTCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        grava();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jFTLogradouroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTLogradouroKeyTyped


    }//GEN-LAST:event_jFTLogradouroKeyTyped

    private void jFTLogradouroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTLogradouroKeyReleased

    }//GEN-LAST:event_jFTLogradouroKeyReleased

    private void jFTLogradouroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTLogradouroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTLogradouroMouseClicked

    private void jFTLogradouroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTLogradouroFocusGained

    }//GEN-LAST:event_jFTLogradouroFocusGained

    private void jFTLogradouroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTLogradouroFocusLost


    }//GEN-LAST:event_jFTLogradouroFocusLost

    private void jButtonGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGravarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            grava();
        }
    }//GEN-LAST:event_jButtonGravarKeyPressed

    private void jFTLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTLogradouroActionPerformed

    private void jFTCepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTCepFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTCepFocusGained

    private void jFTCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTCepFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTCepFocusLost

    private void jFTCepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTCepMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTCepMouseClicked

    private void jFTCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTCepActionPerformed

    private void jFTCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTCepKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTCepKeyReleased

    private void jFTCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTCepKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTCepKeyTyped
    private void grava() {
        try {
            Endereco endereco = new Endereco();
            if (!jFTId.getText().isEmpty()) {
                endereco.setId(Integer.parseInt(jFTId.getText()));
            }
            endereco.setBairro(jFTBairro.getText());
            endereco.setCep(jFTCep.getText());
            endereco.setComplemento(jFTComplemento.getText());
            endereco.setLogradouro(jFTLogradouro.getText());
            endereco.setNumero(jFTNumero.getText());
            endereco.setMunicipio(this.endereco.getMunicipio());
            check=1;
            this.endereco = endereco;
            this.dispose();

        } catch (Exception e) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JFormattedTextField jFTBairro;
    private javax.swing.JFormattedTextField jFTCep;
    private javax.swing.JFormattedTextField jFTComplemento;
    private javax.swing.JFormattedTextField jFTId;
    private javax.swing.JFormattedTextField jFTLogradouro;
    private javax.swing.JFormattedTextField jFTNumero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

   public Endereco showDialog() {
        this.setVisible(true);
        if (check == 1) {
            return endereco;
        } else {
            return null;
        }
    }

    private void preencher(Endereco produto) {
        jFTId.setText(Integer.toString(produto.getId()));
        jFTCep.setText(produto.getCep());
        jFTComplemento.setText(produto.getComplemento());
        jFTBairro.setText(produto.getBairro());
        jFTLogradouro.setText(produto.getLogradouro());
        jFTNumero.setText(produto.getNumero());
    }

    private void formatarCampo() {
        try {

            MaskFormatter mask2 = new MaskFormatter("#####-###");
            mask2.install(jFTCep);

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar", "ERRO", JOptionPane.ERROR);
        }
    }

}
