/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual.servico;

import controller.FicharioFuncionario;
import controller.FicharioServico;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Equipamento;
import model.Funcionario;

import model.Servico;
import visual.produto.CrudProduto;

/**
 *
 * @author Victor
 */
public class AddServico extends javax.swing.JDialog {

    private Servico servico;
    private ArrayList<Funcionario> arrayF = new ArrayList<>();
    private ArrayList<Equipamento> arrayE = new ArrayList<>();
    private int check = 0;

    public AddServico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Adicionar Servico");
        initComponents();

    }

    public AddServico(java.awt.Frame parent, boolean modal, Servico servico) {
        super(parent, modal);
        this.setTitle("Alterar Servico");
        initComponents();
        this.servico = servico;
        preencher(servico);
        for (Equipamento e : servico.getEquipamento()) {
            arrayE.add(e);
        }
        for (Funcionario f : servico.getProfissionais()) {
            arrayF.add(f);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGravar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFTDescricao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonFuncionario = new javax.swing.JButton();
        jButtonEquipamento = new javax.swing.JButton();
        jFTPreco = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jButtonGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGravarKeyPressed(evt);
            }
        });

        jLabel5.setText("Descricão:");

        jFTDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTDescricaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTDescricaoFocusLost(evt);
            }
        });
        jFTDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTDescricaoMouseClicked(evt);
            }
        });
        jFTDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDescricaoActionPerformed(evt);
            }
        });
        jFTDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTDescricaoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTDescricaoKeyTyped(evt);
            }
        });

        jLabel6.setText("Preço:R$");

        jButtonFuncionario.setText("Add Funcionário");
        jButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarioActionPerformed(evt);
            }
        });

        jButtonEquipamento.setText("Add Equipamento");
        jButtonEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEquipamentoActionPerformed(evt);
            }
        });

        jFTPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFTPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTPrecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTPrecoFocusLost(evt);
            }
        });
        jFTPreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTPrecoMouseClicked(evt);
            }
        });
        jFTPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTPrecoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTPrecoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEquipamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jFTDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jFTPreco))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonFuncionario)
                .addGap(18, 18, 18)
                .addComponent(jButtonEquipamento)
                .addGap(18, 18, 18)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        grava();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jFTDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDescricaoKeyTyped


    }//GEN-LAST:event_jFTDescricaoKeyTyped

    private void jFTDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDescricaoKeyReleased

    }//GEN-LAST:event_jFTDescricaoKeyReleased

    private void jFTDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTDescricaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDescricaoMouseClicked

    private void jFTDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDescricaoFocusGained

    }//GEN-LAST:event_jFTDescricaoFocusGained

    private void jFTDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDescricaoFocusLost


    }//GEN-LAST:event_jFTDescricaoFocusLost

    private void jButtonGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGravarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            grava();
        }
    }//GEN-LAST:event_jButtonGravarKeyPressed

    private void jFTDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDescricaoActionPerformed

    private void jButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioActionPerformed
        TelaAddFuncionario tela = new TelaAddFuncionario(null, true, arrayF);
        ArrayList<Funcionario> array = tela.showDialog();
        if (array != null) {
            arrayF = array;
        }
    }//GEN-LAST:event_jButtonFuncionarioActionPerformed

    private void jButtonEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEquipamentoActionPerformed
        TelaAddEquipamento tela = new TelaAddEquipamento(null, true, arrayE);
        ArrayList<Equipamento> array = tela.showDialog();
        if (array != null) {
            arrayE = array;
        }
    }//GEN-LAST:event_jButtonEquipamentoActionPerformed

    private void jFTPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTPrecoFocusGained

    }//GEN-LAST:event_jFTPrecoFocusGained

    private void jFTPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTPrecoFocusLost

    }//GEN-LAST:event_jFTPrecoFocusLost

    private void jFTPrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTPrecoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTPrecoMouseClicked

    private void jFTPrecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTPrecoKeyReleased
        if (jFTPreco.getText().length() > 0) {

            try {
                int pos = jFTPreco.getCaretPosition();
                jFTPreco.commitEdit();
                jFTPreco.setValue(jFTPreco.getValue());
                jFTPreco.setCaretPosition(pos);
            } catch (ParseException ex) {
            }

        }
    }//GEN-LAST:event_jFTPrecoKeyReleased

    private void jFTPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTPrecoKeyTyped

    }//GEN-LAST:event_jFTPrecoKeyTyped
    private void grava() {
        Servico serv = new Servico();
        serv.setDescricao(jFTDescricao.getText());
        String preco = jFTPreco.getText().replaceAll(",", ".");
        serv.setPreco(Double.parseDouble(preco));

        Equipamento[] arr = new Equipamento[arrayE.size()];
        serv.setEquipamento(arrayE.toArray(arr));

        Funcionario[] arr2 = new Funcionario[arrayF.size()];
        serv.setProfissionais(arrayF.toArray(arr2));

        if (arrayF.size() >= 1) {

            if (servico != null) {
                serv.setIdentificador(servico.getIdentificador());
                servico = serv;
                check = 1;
                this.dispose();
            } else
        try {
                FicharioServico fichario = new FicharioServico();
                fichario.add(serv);

                int input = JOptionPane.showConfirmDialog(null, "Registrar outro?", "Gravou com Sucesso", JOptionPane.OK_OPTION);
                if (input != 0) {
                    this.dispose();
                } else {
                    jFTDescricao.setText("");
                    jFTPreco.setText("");
                    arrayF.clear();
                    arrayE.clear();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro, motivo: "
                        + e.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(CrudProduto.class.getName()).log(Level.SEVERE, null, e);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro, motivo: "
                    + "É necessário um mínimo de um funcionário", "Erro", JOptionPane.WARNING_MESSAGE);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEquipamento;
    private javax.swing.JButton jButtonFuncionario;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JFormattedTextField jFTDescricao;
    private javax.swing.JFormattedTextField jFTPreco;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

   public Servico showDialog() {
        this.setVisible(true);
        if (check == 1) {
            return servico;
        } else {
            return null;
        }

    }

    private void preencher(Servico servico) {

        jFTDescricao.setText(servico.getDescricao());
        jFTPreco.setText(Double.toString(servico.getPreco()));
    }

}
