/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual.municipio;

import java.awt.event.KeyEvent;

import model.Municipio;

/**
 *
 * @author Victor
 */
public class AddMunicipio extends javax.swing.JDialog {

    private Municipio produto;

    public AddMunicipio(java.awt.Frame parent, boolean modal, Municipio produto) {
        super(parent, modal);
        this.setTitle("Alterar Municipio");
        initComponents();
        preencher(produto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGravar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFTId = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTNome = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTEstado = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFTPais = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jButtonGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGravarKeyPressed(evt);
            }
        });

        jLabel2.setText("ID:");

        jFTId.setEditable(false);
        jFTId.setEnabled(false);

        jLabel3.setText("Nome:");

        jLabel5.setText("Estado:");

        jFTEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTEstadoFocusLost(evt);
            }
        });
        jFTEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTEstadoMouseClicked(evt);
            }
        });
        jFTEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTEstadoActionPerformed(evt);
            }
        });
        jFTEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTEstadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTEstadoKeyTyped(evt);
            }
        });

        jLabel6.setText("Pais:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTId, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jFTNome)
                            .addComponent(jFTEstado)
                            .addComponent(jFTPais))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFTId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFTPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        grava();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jFTEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTEstadoKeyTyped


    }//GEN-LAST:event_jFTEstadoKeyTyped

    private void jFTEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTEstadoKeyReleased

    }//GEN-LAST:event_jFTEstadoKeyReleased

    private void jFTEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTEstadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTEstadoMouseClicked

    private void jFTEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTEstadoFocusGained

    }//GEN-LAST:event_jFTEstadoFocusGained

    private void jFTEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTEstadoFocusLost


    }//GEN-LAST:event_jFTEstadoFocusLost

    private void jButtonGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGravarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            grava();
        }
    }//GEN-LAST:event_jButtonGravarKeyPressed

    private void jFTEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTEstadoActionPerformed
    private void grava() {
        try {
            Municipio prod = new Municipio();
            if (!jFTId.getText().isEmpty()) {
                prod.setId(Integer.parseInt(jFTId.getText()));
            }
            prod.setNome(jFTNome.getText());
            prod.setEstado(jFTEstado.getText());
            prod.setPais(jFTPais.getText());

            produto = prod;
            this.dispose();

        } catch (Exception e) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JFormattedTextField jFTEstado;
    private javax.swing.JFormattedTextField jFTId;
    private javax.swing.JFormattedTextField jFTNome;
    private javax.swing.JFormattedTextField jFTPais;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    Municipio showDialog() {
        this.setVisible(true);
        return produto;

    }

    private void preencher(Municipio produto) {
        jFTId.setText(Integer.toString(produto.getId()));
        jFTNome.setText(produto.getNome());
        jFTEstado.setText(produto.getEstado());
        jFTPais.setText(produto.getPais());
    }

}
