/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual.principal;

import java.awt.Component;
import java.awt.Container;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JTextField;
import javax.swing.MenuElement;
import model.Cliente;
import model.Conta;
import visual.cliente.CrudPessoaF;
import visual.cliente.CrudPessoaJ;
import visual.cliente.CrudPet;
import visual.cliente.CrudVeiculo;
import visual.conta.AlterConta;
import visual.conta.CrudConta;
import visual.endereco.CrudEndereco;
import visual.equipamento.CrudEquipamento;
import visual.fatura.CrudFatura;
import visual.funcionario.CrudFuncionario;
import visual.municipio.CrudMunicipio;
import visual.produto.CrudProduto;
import visual.servico.CrudServico;

/**
 *
 * @author Victor
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaPrincipal() {
        initComponents();
        fechaTelas();
        this.setTitle("Tela Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDP = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConta = new javax.swing.JMenu();
        jCheckBoxMenuItemContas = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemFaturas = new javax.swing.JCheckBoxMenuItem();
        jMenuEmpresa = new javax.swing.JMenu();
        jCheckBoxMenuItemProdutos = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemServicos = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemFuncionarios = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemEquipamentos = new javax.swing.JCheckBoxMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jCheckBoxMenuItemClientesF = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemClientesJ = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemEnderecos = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemMunicipios = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemVeiculos = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemPets = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDPLayout = new javax.swing.GroupLayout(jDP);
        jDP.setLayout(jDPLayout);
        jDPLayout.setHorizontalGroup(
            jDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jDPLayout.setVerticalGroup(
            jDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jMenuConta.setText("Conta");

        jCheckBoxMenuItemContas.setText("Contas");
        jCheckBoxMenuItemContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemContasActionPerformed(evt);
            }
        });
        jMenuConta.add(jCheckBoxMenuItemContas);

        jCheckBoxMenuItemFaturas.setSelected(true);
        jCheckBoxMenuItemFaturas.setText("Faturas");
        jCheckBoxMenuItemFaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemFaturasActionPerformed(evt);
            }
        });
        jMenuConta.add(jCheckBoxMenuItemFaturas);

        jMenuBar1.add(jMenuConta);

        jMenuEmpresa.setText("Empresa");

        jCheckBoxMenuItemProdutos.setSelected(true);
        jCheckBoxMenuItemProdutos.setText("Produtos");
        jCheckBoxMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jCheckBoxMenuItemProdutos);

        jCheckBoxMenuItemServicos.setSelected(true);
        jCheckBoxMenuItemServicos.setText("Serviços");
        jCheckBoxMenuItemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemServicosActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jCheckBoxMenuItemServicos);

        jCheckBoxMenuItemFuncionarios.setSelected(true);
        jCheckBoxMenuItemFuncionarios.setText("Funcionários");
        jCheckBoxMenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemFuncionariosActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jCheckBoxMenuItemFuncionarios);

        jCheckBoxMenuItemEquipamentos.setSelected(true);
        jCheckBoxMenuItemEquipamentos.setText("Equipamentos");
        jCheckBoxMenuItemEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemEquipamentosActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jCheckBoxMenuItemEquipamentos);

        jMenuBar1.add(jMenuEmpresa);

        jMenuCliente.setText("Cliente");

        jCheckBoxMenuItemClientesF.setSelected(true);
        jCheckBoxMenuItemClientesF.setText("Cliente Físico");
        jCheckBoxMenuItemClientesF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemClientesFActionPerformed(evt);
            }
        });
        jMenuCliente.add(jCheckBoxMenuItemClientesF);

        jCheckBoxMenuItemClientesJ.setSelected(true);
        jCheckBoxMenuItemClientesJ.setText("Cliente Jurídico");
        jCheckBoxMenuItemClientesJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemClientesJActionPerformed(evt);
            }
        });
        jMenuCliente.add(jCheckBoxMenuItemClientesJ);

        jCheckBoxMenuItemEnderecos.setSelected(true);
        jCheckBoxMenuItemEnderecos.setText("Endereços");
        jCheckBoxMenuItemEnderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemEnderecosActionPerformed(evt);
            }
        });
        jMenuCliente.add(jCheckBoxMenuItemEnderecos);

        jCheckBoxMenuItemMunicipios.setSelected(true);
        jCheckBoxMenuItemMunicipios.setText("Municípios");
        jCheckBoxMenuItemMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemMunicipiosActionPerformed(evt);
            }
        });
        jMenuCliente.add(jCheckBoxMenuItemMunicipios);

        jCheckBoxMenuItemVeiculos.setSelected(true);
        jCheckBoxMenuItemVeiculos.setText("Veículos");
        jCheckBoxMenuItemVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemVeiculosActionPerformed(evt);
            }
        });
        jMenuCliente.add(jCheckBoxMenuItemVeiculos);

        jCheckBoxMenuItemPets.setSelected(true);
        jCheckBoxMenuItemPets.setText("Pets");
        jCheckBoxMenuItemPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemPetsActionPerformed(evt);
            }
        });
        jMenuCliente.add(jCheckBoxMenuItemPets);

        jMenuBar1.add(jMenuCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemProdutosActionPerformed
        addCentered(new CrudProduto());
    }//GEN-LAST:event_jCheckBoxMenuItemProdutosActionPerformed

    private void jCheckBoxMenuItemContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemContasActionPerformed
        addCentered(new CrudContaTeste());
    }//GEN-LAST:event_jCheckBoxMenuItemContasActionPerformed

    private void jCheckBoxMenuItemClientesFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemClientesFActionPerformed
        addCentered(new CrudPessoaF());
    }//GEN-LAST:event_jCheckBoxMenuItemClientesFActionPerformed

    private void jCheckBoxMenuItemFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemFaturasActionPerformed
        addCentered(new CrudFatura());
    }//GEN-LAST:event_jCheckBoxMenuItemFaturasActionPerformed

    private void jCheckBoxMenuItemServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemServicosActionPerformed
        addCentered(new CrudServico());
    }//GEN-LAST:event_jCheckBoxMenuItemServicosActionPerformed

    private void jCheckBoxMenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemFuncionariosActionPerformed
        addCentered(new CrudFuncionario());
    }//GEN-LAST:event_jCheckBoxMenuItemFuncionariosActionPerformed

    private void jCheckBoxMenuItemEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemEquipamentosActionPerformed
        addCentered(new CrudEquipamento());
    }//GEN-LAST:event_jCheckBoxMenuItemEquipamentosActionPerformed

    private void jCheckBoxMenuItemClientesJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemClientesJActionPerformed
        addCentered(new CrudPessoaJ());
    }//GEN-LAST:event_jCheckBoxMenuItemClientesJActionPerformed

    private void jCheckBoxMenuItemEnderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemEnderecosActionPerformed
        addCentered(new CrudEndereco());
    }//GEN-LAST:event_jCheckBoxMenuItemEnderecosActionPerformed

    private void jCheckBoxMenuItemMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemMunicipiosActionPerformed
        addCentered(new CrudMunicipio());
    }//GEN-LAST:event_jCheckBoxMenuItemMunicipiosActionPerformed

    private void jCheckBoxMenuItemVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemVeiculosActionPerformed
        addCentered(new CrudVeiculo());
    }//GEN-LAST:event_jCheckBoxMenuItemVeiculosActionPerformed

    private void jCheckBoxMenuItemPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemPetsActionPerformed
        addCentered(new CrudPet());
    }//GEN-LAST:event_jCheckBoxMenuItemPetsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    public void addCentered(JInternalFrame jif) {
        fechaTelas();
        jDP.add(jif);
        jif.setLocation((jDP.getWidth() - jif.getWidth()) / 2, (jDP.getHeight() - jif.getHeight()) / 2);
        jif.setVisible(true);
    }

    private void fechaTelas() {
        if (jDP.getComponents().length > 0) {
            jDP.removeAll();
            jDP.repaint();
        }

        for (MenuElement x : jMenuBar1.getSubElements()) {
            if (x instanceof JMenu m) {

                for (Component d : m.getMenuComponents()) {
                    if (d instanceof JCheckBoxMenuItem f) {
                        f.setSelected(false);
                    }

                }

            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemClientesF;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemClientesJ;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemContas;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEnderecos;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEquipamentos;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemFaturas;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemFuncionarios;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemMunicipios;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemPets;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemProdutos;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemServicos;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemVeiculos;
    private javax.swing.JDesktopPane jDP;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuConta;
    private javax.swing.JMenu jMenuEmpresa;
    // End of variables declaration//GEN-END:variables
}
