/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import java.awt.Frame;
import java.text.DateFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

import model.Item;
import model.Produto;

/**
 *
 * @author Victor
 */
public class AddDefault extends javax.swing.JDialog {

    /**
     * Creates new form CrudAlterConta
     */
    public AddDefault() {

        this.setTitle("Cadastro de XXXX");
        initComponents();
        formatarCampo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFTDataA = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTDataA1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTDataA2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFTDataA3 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFTDataA4 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonVoltar.setText("<<<");
        jButtonVoltar.setFocusable(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca:");

        jFTDataA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTDataAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTDataAFocusLost(evt);
            }
        });
        jFTDataA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDataAActionPerformed(evt);
            }
        });
        jFTDataA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTDataAKeyReleased(evt);
            }
        });

        jLabel3.setText("Modelo:");

        jFTDataA1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTDataA1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTDataA1FocusLost(evt);
            }
        });
        jFTDataA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDataA1ActionPerformed(evt);
            }
        });
        jFTDataA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTDataA1KeyReleased(evt);
            }
        });

        jLabel5.setText("Cor:");

        jFTDataA2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTDataA2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTDataA2FocusLost(evt);
            }
        });
        jFTDataA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDataA2ActionPerformed(evt);
            }
        });
        jFTDataA2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTDataA2KeyReleased(evt);
            }
        });

        jLabel6.setText("Placa:");

        jFTDataA3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTDataA3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTDataA3FocusLost(evt);
            }
        });
        jFTDataA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDataA3ActionPerformed(evt);
            }
        });
        jFTDataA3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTDataA3KeyReleased(evt);
            }
        });

        jLabel7.setText("Vaga:");

        jFTDataA4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTDataA4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTDataA4FocusLost(evt);
            }
        });
        jFTDataA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDataA4ActionPerformed(evt);
            }
        });
        jFTDataA4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTDataA4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonVoltar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTDataA, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jFTDataA1)
                            .addComponent(jFTDataA2)
                            .addComponent(jFTDataA3)
                            .addComponent(jFTDataA4))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFTDataA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFTDataA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTDataA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFTDataA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFTDataA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed

    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed

    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jFTDataAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataAFocusGained

    }//GEN-LAST:event_jFTDataAFocusGained

    private void jFTDataAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDataAActionPerformed

    }//GEN-LAST:event_jFTDataAActionPerformed

    private void jFTDataAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataAFocusLost

    }//GEN-LAST:event_jFTDataAFocusLost

    private void jFTDataAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDataAKeyReleased

    }//GEN-LAST:event_jFTDataAKeyReleased

    private void jFTDataA1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA1FocusGained

    private void jFTDataA1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA1FocusLost

    private void jFTDataA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDataA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA1ActionPerformed

    private void jFTDataA1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDataA1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA1KeyReleased

    private void jFTDataA2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA2FocusGained

    private void jFTDataA2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA2FocusLost

    private void jFTDataA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDataA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA2ActionPerformed

    private void jFTDataA2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDataA2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA2KeyReleased

    private void jFTDataA3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA3FocusGained

    private void jFTDataA3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA3FocusLost

    private void jFTDataA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDataA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA3ActionPerformed

    private void jFTDataA3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDataA3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA3KeyReleased

    private void jFTDataA4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA4FocusGained

    private void jFTDataA4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTDataA4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA4FocusLost

    private void jFTDataA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDataA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA4ActionPerformed

    private void jFTDataA4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDataA4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataA4KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JFormattedTextField jFTDataA;
    private javax.swing.JFormattedTextField jFTDataA1;
    private javax.swing.JFormattedTextField jFTDataA2;
    private javax.swing.JFormattedTextField jFTDataA3;
    private javax.swing.JFormattedTextField jFTDataA4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    void showDialog() {
        this.setVisible(true);

    }

    private void formatarCampo() {
        try {
            MaskFormatter mask = new MaskFormatter("**/**/****");
            MaskFormatter mask2 = new MaskFormatter("##");
            mask.setPlaceholder("__/__/____");
            mask2.setPlaceholder("");



        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar", "ERRO", JOptionPane.ERROR);
        }
    }

}