/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import controller.FicharioProduto;
import dao.ProdutoDAO;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

import model.Produto;
import recursos.ImagemFichario;

/**
 *
 * @author Victor
 */
public class AddProduto extends javax.swing.JDialog {

    private Produto produto;
    MaskFormatter mask = new MaskFormatter();
    MaskFormatter mask2 = new MaskFormatter();

    public AddProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Cadastro de Produto");
        initComponents();
        formatarCampo();

    }

    public AddProduto(java.awt.Frame parent, boolean modal, Produto produto) {
        super(parent, modal);
        this.setTitle("Alterar Produto");
        initComponents();
        formatarCampo();
        preencher(produto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGravar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFTId = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTDescricao = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTPreco = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFTMarca = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFTValidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jButtonGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGravarKeyPressed(evt);
            }
        });

        jLabel2.setText("ID:");

        jFTId.setEditable(false);
        jFTId.setEnabled(false);

        jLabel3.setText("Descrição:");

        jLabel5.setText("Preço: R$");

        jFTPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFTPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTPrecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTPrecoFocusLost(evt);
            }
        });
        jFTPreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTPrecoMouseClicked(evt);
            }
        });
        jFTPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTPrecoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTPrecoKeyTyped(evt);
            }
        });

        jLabel6.setText("Marca:");

        jLabel7.setText("Validade:");

        jFTValidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTValidadeFocusGained(evt);
            }
        });
        jFTValidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTValidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTValidadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTId, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jFTDescricao)
                            .addComponent(jFTPreco)
                            .addComponent(jFTMarca)
                            .addComponent(jFTValidade))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFTId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFTValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        grava();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jFTPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTPrecoKeyTyped


    }//GEN-LAST:event_jFTPrecoKeyTyped

    private void jFTPrecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTPrecoKeyReleased
        if (jFTPreco.getText().length() > 0) {

            try {
                int pos = jFTPreco.getCaretPosition();
                jFTPreco.commitEdit();
                jFTPreco.setValue(jFTPreco.getValue());
                jFTPreco.setCaretPosition(pos);
            } catch (ParseException ex) {
            }

        }
    }//GEN-LAST:event_jFTPrecoKeyReleased

    private void jFTPrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTPrecoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTPrecoMouseClicked

    private void jFTPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTPrecoFocusGained

    }//GEN-LAST:event_jFTPrecoFocusGained

    private void jFTPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTPrecoFocusLost


    }//GEN-LAST:event_jFTPrecoFocusLost

    private void jFTValidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTValidadeKeyTyped

    }//GEN-LAST:event_jFTValidadeKeyTyped

    private void jFTValidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTValidadeKeyReleased
        if (!jFTValidade.getText().contains("_"))
        try {
            int dia, mes, ano, index;
            String texto = jFTValidade.getText();
            index = texto.indexOf("/");
            dia = Integer.parseInt(texto.substring(0, index));
            texto = texto.substring(index + 1);
            index = texto.indexOf("/");
            mes = Integer.parseInt(texto.substring(0, index));
            texto = texto.substring(index + 1);
            ano = Integer.parseInt(texto);
            LocalDate date = LocalDate.of(ano, mes, dia);
            jButtonGravar.requestFocus();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jFTValidadeKeyReleased

    private void jButtonGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGravarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            grava();
        }
    }//GEN-LAST:event_jButtonGravarKeyPressed

    private void jFTValidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTValidadeFocusGained
       jFTValidade.setCaretPosition(0);
    }//GEN-LAST:event_jFTValidadeFocusGained
    private void grava() {
        try {
            Produto prod = new Produto();
            if (!jFTId.getText().isEmpty()) {
                prod.setIdentificador(Integer.parseInt(jFTId.getText()));
            }
            prod.setDescricao(jFTDescricao.getText());
            String preco = jFTPreco.getText().replaceAll(",", ".");
            prod.setPreco(Double.parseDouble(preco));
            prod.setMarca(jFTMarca.getText());
            int dia, mes, ano, index;
            String texto = jFTValidade.getText();
            index = texto.indexOf("-");
            dia = Integer.parseInt(texto.substring(0, index));
            texto = texto.substring(index + 1);
            index = texto.indexOf("-");
            mes = Integer.parseInt(texto.substring(0, index));
            texto = texto.substring(index + 1);
            ano = Integer.parseInt(texto);
            LocalDate date = LocalDate.of(ano, mes, dia);
            prod.setValidade(date);
            produto = prod;

            if (jFTId.getText().length() > 0) {
                this.dispose();
            } else {
                gravaBD();
                int input = JOptionPane.showConfirmDialog(null, "Registrar outro?","Escolha",JOptionPane.OK_OPTION);
                if (input != 0) {
                    this.dispose();
                } else {
                    Container con = this.getContentPane();
                    for (Component c : con.getComponents()) {
                        if (c instanceof JTextField) {
                            JTextField j = (JTextField) c;
                            j.setText("");
                        }
                    }
                    jFTValidade.setText("__-__-____");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro, motivo: "
                    + e.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JFormattedTextField jFTDescricao;
    private javax.swing.JFormattedTextField jFTId;
    private javax.swing.JFormattedTextField jFTMarca;
    private javax.swing.JFormattedTextField jFTPreco;
    private javax.swing.JFormattedTextField jFTValidade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    Produto showDialog() {
        this.setVisible(true);
        return produto;

    }

    private void formatarCampo() {
        try {
            mask.setMask("**-**-****");
            mask.setPlaceholder("__-__-____");
            mask.install(jFTValidade);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar", "ERRO", JOptionPane.ERROR);
        }
    }

    private void preencher(Produto produto) {
        jFTId.setText(Integer.toString(produto.getIdentificador()));
        jFTDescricao.setText(produto.getDescricao());
        jFTPreco.setText(Double.toString(produto.getPreco()));
        jFTMarca.setText(produto.getMarca());
        int dia, mes, ano;
        dia = produto.getValidade().getDayOfMonth();
        mes = produto.getValidade().getMonthValue();
        ano = produto.getValidade().getYear();
        String diaFormat = String.format("%02d", dia);
        String mesFormat = String.format("%02d", mes);
        jFTValidade.setText(diaFormat + "-" + mesFormat + "-" + ano);
    }

    private void gravaBD() {
        if (produto != null) {
            try {
                FicharioProduto fichario = new FicharioProduto();
                fichario.add(produto);
                ImagemFichario imagem = new ImagemFichario();
                JOptionPane.showMessageDialog(null, "O dado foi gravado corretamente.",
                        "Sucesso", JOptionPane.ERROR_MESSAGE, imagem.sucesso());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro, motivo: "
                        + e.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

}
