/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual.equipamento;

import controller.FicharioEquipamento;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Equipamento;

import model.Municipio;

/**
 *
 * @author Victor
 */
public class AddEquipamento extends javax.swing.JDialog {

    private Equipamento equipamento;
    private int check = 0;

    public AddEquipamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Adicionar Equipamento");
        initComponents();

    }

    public AddEquipamento(java.awt.Frame parent, boolean modal, Equipamento equipamento) {
        super(parent, modal);
        this.setTitle("Alterar Equipamento");
        initComponents();
        preencher(equipamento);
        this.equipamento = equipamento;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGravar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jFTDescricao = new javax.swing.JFormattedTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jButtonGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGravarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 70, 121, 36));

        jLabel6.setText("Descrição:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jFTDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(jFTDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 30));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 20, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        grava();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGravarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            grava();
        }
    }//GEN-LAST:event_jButtonGravarKeyPressed

    private void jFTDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDescricaoActionPerformed
    private void grava() {
        Equipamento equi = new Equipamento();
        equi.setDescricao(jFTDescricao.getText());
        if (equipamento != null) {
            equi.setIdentificador(equipamento.getIdentificador());
            equipamento = equi;
            check = 1;
            this.dispose();
        } else
        try {
            FicharioEquipamento fichario = new FicharioEquipamento();
            fichario.add(equi);

            int input = JOptionPane.showConfirmDialog(null, "Registrar outro?", "Gravou com Sucesso", JOptionPane.OK_OPTION);
            if (input != 0) {
                this.dispose();
            } else {
                jFTDescricao.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro, motivo: "
                    + e.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JFormattedTextField jFTDescricao;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

   public Equipamento showDialog() {
        this.setVisible(true);
        if (check == 1) {
            return equipamento;
        } else {
            return null;
        }

    }

    private void preencher(Equipamento equipamento) {

        jFTDescricao.setText(equipamento.getDescricao());
    }

}
